package com.example.test.framework;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import com.example.mock.pojo.Entity;
import com.example.mock.pojo.Field;
import com.example.mock.pojo.TenantConfig;

public class ConfigReader {
	
	
	private TenantConfig config;
	public ConfigReader(TenantConfig config) {
		this.config = config;		
	}
	
	public List<Entity> getEntities(){
		
		return config.getEntities();
		
	}
	
	public HashMap<String,List<DynamicField>> mapEntityToFields(){
	  HashMap<String,List<DynamicField>> fields = new HashMap<>();
		for(Entity entity : config.getEntities()){
			List<DynamicField> dfs = new ArrayList<DynamicField>();
			for(Field f : entity.getFields()){
				DynamicField df = new DynamicField();
				df.setEntity(entity.getEntity());
				df.setFieldname(f.getName());
				df.setRequired(f.getRequired());
				df.setType(f.getType());
				df.setAutogenerated(f.getAutogenerated());
				dfs.add(df);
				
			}
			fields.put(entity.getEntity(),dfs);
		}
		
		return fields;
	}
	

}
