package com.example.mock.pojo;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class Field {

@SerializedName("name")
@Expose
private String name;
@SerializedName("type")
@Expose
private String type;
@SerializedName("required")
@Expose
private Boolean required;
@SerializedName("occurance")
@Expose
private String occurance;
@SerializedName("validations")
@Expose
private Validations validations;

@SerializedName("autogenerated")
@Expose
private Boolean autogenerated =false;

public String getName() {
return name;
}

public void setName(String name) {
this.name = name;
}

public String getType() {
return type;
}

public void setType(String type) {
this.type = type;
}

public Boolean getRequired() {
return required;
}

public void setRequired(Boolean required) {
this.required = required;
}

public String getOccurance() {
return occurance;
}

public void setOccurance(String occurance) {
this.occurance = occurance;
}

public Validations getValidations() {
return validations;
}

public void setValidations(Validations validations) {
this.validations = validations;
}

public Boolean getAutogenerated() {
	return autogenerated;
}

public void setAutogenerated(Boolean autogenerated) {
	this.autogenerated = autogenerated;
}



}