package com.example.functional.test;

public class DynamicField {
	
	private String entity;
	private String fieldname;
	private Boolean required;
	private String type;
	private Boolean autogenerated =false;
	
	public String getEntity() {
		return entity;
	}
	public void setEntity(String entity) {
		this.entity = entity;
	}
	public String getFieldname() {
		return fieldname;
	}
	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}
	public Boolean getRequired() {
		return required;
	}
	public void setRequired(Boolean required) {
		this.required = required;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public Boolean getAutogenerated() {
		return autogenerated;
	}
	public void setAutogenerated(Boolean autogenerated) {
		this.autogenerated = autogenerated;
	}
	

}
